package com.test.edeklaracje;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-12-15T17:38:46.089+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/", name = "GateServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GateServicePortType {

    @WebMethod(action = "urn:sendUnsignDocument")
    @RequestWrapper(localName = "sendUnsignDocument", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendUnsignDocument")
    @ResponseWrapper(localName = "sendUnsignDocumentResponse", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendUnsignDocumentResponse")
    public void sendUnsignDocument(

        @WebParam(name = "document", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        byte[] document,
        @WebParam(name = "language", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        java.lang.String language,
        @WebParam(name = "signatureType", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        java.lang.String signatureType,
        @WebParam(mode = WebParam.Mode.OUT, name = "refId", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> refId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.Integer> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusOpis", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> statusOpis
    );

    @WebMethod(action = "urn:sendDocument")
    @RequestWrapper(localName = "sendDocument", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendDocument")
    @ResponseWrapper(localName = "sendDocumentResponse", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendDocumentResponse")
    public void sendDocument(

        @WebParam(name = "document", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        byte[] document,
        @WebParam(mode = WebParam.Mode.OUT, name = "refId", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> refId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.Integer> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusOpis", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> statusOpis
    );

    @WebMethod(action = "urn:sendDocumentWithAttachment")
    @RequestWrapper(localName = "sendDocumentWithAttachment", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendDocumentWithAttachment")
    @ResponseWrapper(localName = "sendDocumentWithAttachmentResponse", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.SendDocumentWithAttachmentResponse")
    public void sendDocumentWithAttachment(

        @WebParam(name = "attachment", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        byte[] attachment,
        @WebParam(name = "document", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        byte[] document,
        @WebParam(mode = WebParam.Mode.OUT, name = "refId", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> refId,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.Integer> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusOpis", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> statusOpis
    );

    @WebMethod(action = "urn:requestUPO")
    @RequestWrapper(localName = "requestUPO", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.RequestUPO")
    @ResponseWrapper(localName = "requestUPOResponse", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd", className = "com.test.edeklaracje.RequestUPOResponse")
    public void requestUPO(

        @WebParam(name = "refId", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        java.lang.String refId,
        @WebParam(name = "language", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        java.lang.String language,
        @WebParam(mode = WebParam.Mode.OUT, name = "upo", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> upo,
        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.Integer> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "statusOpis", targetNamespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")
        jakarta.xml.ws.Holder<java.lang.String> statusOpis
    );
}
